# Generated by go2rpm 1.18.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/slsa-framework/slsa-verifier
%global goipath         github.com/slsa-framework/slsa-verifier
Version:                2.7.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Verify provenance from SLSA compliant builders.}

%global golicenses      LICENSE
%global godocs          docs README.md RELEASE.md SECURITY.md SHA256SUM.md\\\
                        requirements-lint.txt actions/installer/README.md\\\
                        cli/experimental/service/README.md\\\
                        experimental/maven-plugin/README.md

Name:           slsa-verifier
Release:        %autorelease
Summary:        Verify provenance from SLSA compliant builders

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cli/experimental/service cli/slsa-verifier; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs README.md RELEASE.md SECURITY.md SHA256SUM.md requirements-lint.txt
%doc actions/installer/README.md cli/experimental/service/README.md
%doc experimental/maven-plugin/README.md
%{_bindir}/service
%{_bindir}/slsa-verifier
%endif

%gopkgfiles

%changelog
%autochangelog
